# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTerrainMaterialTable extends _ModuleTable

var id: ContinuumTerrainMaterialIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "terrain_material")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumTerrainMaterial")

static func create(p_local_db: LocalDatabase) -> ContinuumTerrainMaterialTable:
	var table: ContinuumTerrainMaterialTable = ContinuumTerrainMaterialTable.new()
	table._db = p_local_db
	table.id = ContinuumTerrainMaterialIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumTerrainMaterial]:
	var rows: Array = super()
	var typed_array: Array[ContinuumTerrainMaterial] = []
	typed_array.assign(rows)
	return typed_array
