# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumBuildingTable extends _ModuleTable

var id: ContinuumBuildingIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "building")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumBuilding")

static func create(p_local_db: LocalDatabase) -> ContinuumBuildingTable:
	var table: ContinuumBuildingTable = ContinuumBuildingTable.new()
	table._db = p_local_db
	table.id = ContinuumBuildingIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumBuilding]:
	var rows: Array = super()
	var typed_array: Array[ContinuumBuilding] = []
	typed_array.assign(rows)
	return typed_array
