# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumWorldGeometryTable extends _ModuleTable

var id: ContinuumWorldGeometryIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "world_geometry")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumWorldGeometry")

static func create(p_local_db: LocalDatabase) -> ContinuumWorldGeometryTable:
	var table: ContinuumWorldGeometryTable = ContinuumWorldGeometryTable.new()
	table._db = p_local_db
	table.id = ContinuumWorldGeometryIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumWorldGeometry]:
	var rows: Array = super()
	var typed_array: Array[ContinuumWorldGeometry] = []
	typed_array.assign(rows)
	return typed_array
