# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumBuildingIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, ContinuumBuilding] = {}

func _init() -> void:
	set_meta("table_name", "building")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> ContinuumBuildingIdUniqueIndex:
	var index: ContinuumBuildingIdUniqueIndex = ContinuumBuildingIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> ContinuumBuilding:
	return _cache.get(col_val, null)
