# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTerrainColumnChunkTable extends _ModuleTable

var id: ContinuumTerrainColumnChunkIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "terrain_column_chunk")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumTerrainColumnChunk")

static func create(p_local_db: LocalDatabase) -> ContinuumTerrainColumnChunkTable:
	var table: ContinuumTerrainColumnChunkTable = ContinuumTerrainColumnChunkTable.new()
	table._db = p_local_db
	table.id = ContinuumTerrainColumnChunkIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumTerrainColumnChunk]:
	var rows: Array = super()
	var typed_array: Array[ContinuumTerrainColumnChunk] = []
	typed_array.assign(rows)
	return typed_array
