# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumBuildingThermalPropertyTable extends _ModuleTable

var building_id: ContinuumBuildingThermalPropertyBuildingIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "building_thermal_property")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumBuildingThermalProperty")

static func create(p_local_db: LocalDatabase) -> ContinuumBuildingThermalPropertyTable:
	var table: ContinuumBuildingThermalPropertyTable = ContinuumBuildingThermalPropertyTable.new()
	table._db = p_local_db
	table.building_id = ContinuumBuildingThermalPropertyBuildingIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumBuildingThermalProperty]:
	var rows: Array = super()
	var typed_array: Array[ContinuumBuildingThermalProperty] = []
	typed_array.assign(rows)
	return typed_array
