# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumExcavationDesignationTable extends _ModuleTable

var id: ContinuumExcavationDesignationIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "excavation_designation")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumExcavationDesignation")

static func create(p_local_db: LocalDatabase) -> ContinuumExcavationDesignationTable:
	var table: ContinuumExcavationDesignationTable = ContinuumExcavationDesignationTable.new()
	table._db = p_local_db
	table.id = ContinuumExcavationDesignationIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumExcavationDesignation]:
	var rows: Array = super()
	var typed_array: Array[ContinuumExcavationDesignation] = []
	typed_array.assign(rows)
	return typed_array
