# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumProductionPolicyResourceUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, ContinuumProductionPolicy] = {}

func _init() -> void:
	set_meta("table_name", "production_policy")
	set_meta("field_name", "resource")

static func create(p_local_db: LocalDatabase) -> ContinuumProductionPolicyResourceUniqueIndex:
	var index: ContinuumProductionPolicyResourceUniqueIndex = ContinuumProductionPolicyResourceUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: ContinuumResourceKind) -> ContinuumProductionPolicy:
	var key: Variant = _key(col_val)
	if key == null: return null
	return _cache.get(key, null)
