# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumConfigTable extends _ModuleTable

var id: ContinuumConfigIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "config")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumConfig")

static func create(p_local_db: LocalDatabase) -> ContinuumConfigTable:
	var table: ContinuumConfigTable = ContinuumConfigTable.new()
	table._db = p_local_db
	table.id = ContinuumConfigIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumConfig]:
	var rows: Array = super()
	var typed_array: Array[ContinuumConfig] = []
	typed_array.assign(rows)
	return typed_array
