# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumWorldSeedTable extends _ModuleTable

var id: ContinuumWorldSeedIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "world_seed")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumWorldSeed")

static func create(p_local_db: LocalDatabase) -> ContinuumWorldSeedTable:
	var table: ContinuumWorldSeedTable = ContinuumWorldSeedTable.new()
	table._db = p_local_db
	table.id = ContinuumWorldSeedIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumWorldSeed]:
	var rows: Array = super()
	var typed_array: Array[ContinuumWorldSeed] = []
	typed_array.assign(rows)
	return typed_array
