# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumWorldGeometryIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, ContinuumWorldGeometry] = {}

func _init() -> void:
	set_meta("table_name", "world_geometry")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> ContinuumWorldGeometryIdUniqueIndex:
	var index: ContinuumWorldGeometryIdUniqueIndex = ContinuumWorldGeometryIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> ContinuumWorldGeometry:
	return _cache.get(col_val, null)
