# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTerrainOverviewChunkTable extends _ModuleTable

var id: ContinuumTerrainOverviewChunkIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "terrain_overview_chunk")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumTerrainOverviewChunk")

static func create(p_local_db: LocalDatabase) -> ContinuumTerrainOverviewChunkTable:
	var table: ContinuumTerrainOverviewChunkTable = ContinuumTerrainOverviewChunkTable.new()
	table._db = p_local_db
	table.id = ContinuumTerrainOverviewChunkIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumTerrainOverviewChunk]:
	var rows: Array = super()
	var typed_array: Array[ContinuumTerrainOverviewChunk] = []
	typed_array.assign(rows)
	return typed_array
