# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumAlertCodeUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[String, ContinuumAlert] = {}

func _init() -> void:
	set_meta("table_name", "alert")
	set_meta("field_name", "code")

static func create(p_local_db: LocalDatabase) -> ContinuumAlertCodeUniqueIndex:
	var index: ContinuumAlertCodeUniqueIndex = ContinuumAlertCodeUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: String) -> ContinuumAlert:
	return _cache.get(col_val, null)
