# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumBuildingThermalPropertyBuildingIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, ContinuumBuildingThermalProperty] = {}

func _init() -> void:
	set_meta("table_name", "building_thermal_property")
	set_meta("field_name", "building_id")

static func create(p_local_db: LocalDatabase) -> ContinuumBuildingThermalPropertyBuildingIdUniqueIndex:
	var index: ContinuumBuildingThermalPropertyBuildingIdUniqueIndex = ContinuumBuildingThermalPropertyBuildingIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> ContinuumBuildingThermalProperty:
	return _cache.get(col_val, null)
