# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumColonistTable extends _ModuleTable

var id: ContinuumColonistIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "colonist")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumColonist")

static func create(p_local_db: LocalDatabase) -> ContinuumColonistTable:
	var table: ContinuumColonistTable = ContinuumColonistTable.new()
	table._db = p_local_db
	table.id = ContinuumColonistIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumColonist]:
	var rows: Array = super()
	var typed_array: Array[ContinuumColonist] = []
	typed_array.assign(rows)
	return typed_array
