# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumItemStackTable extends _ModuleTable

var id: ContinuumItemStackIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "item_stack")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumItemStack")

static func create(p_local_db: LocalDatabase) -> ContinuumItemStackTable:
	var table: ContinuumItemStackTable = ContinuumItemStackTable.new()
	table._db = p_local_db
	table.id = ContinuumItemStackIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumItemStack]:
	var rows: Array = super()
	var typed_array: Array[ContinuumItemStack] = []
	typed_array.assign(rows)
	return typed_array
