# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumSpeedControlTable extends _ModuleTable

var id: ContinuumSpeedControlIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "speed_control")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumSpeedControl")

static func create(p_local_db: LocalDatabase) -> ContinuumSpeedControlTable:
	var table: ContinuumSpeedControlTable = ContinuumSpeedControlTable.new()
	table._db = p_local_db
	table.id = ContinuumSpeedControlIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumSpeedControl]:
	var rows: Array = super()
	var typed_array: Array[ContinuumSpeedControl] = []
	typed_array.assign(rows)
	return typed_array
