# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTileTable extends _ModuleTable

var id: ContinuumTileIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "tile")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumTile")

static func create(p_local_db: LocalDatabase) -> ContinuumTileTable:
	var table: ContinuumTileTable = ContinuumTileTable.new()
	table._db = p_local_db
	table.id = ContinuumTileIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumTile]:
	var rows: Array = super()
	var typed_array: Array[ContinuumTile] = []
	typed_array.assign(rows)
	return typed_array
