# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTerrainTable extends _ModuleTable

var tile_id: ContinuumTerrainTileIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "terrain")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumTerrain")

static func create(p_local_db: LocalDatabase) -> ContinuumTerrainTable:
	var table: ContinuumTerrainTable = ContinuumTerrainTable.new()
	table._db = p_local_db
	table.tile_id = ContinuumTerrainTileIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumTerrain]:
	var rows: Array = super()
	var typed_array: Array[ContinuumTerrain] = []
	typed_array.assign(rows)
	return typed_array
