# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTerrainMaterialIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, ContinuumTerrainMaterial] = {}

func _init() -> void:
	set_meta("table_name", "terrain_material")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> ContinuumTerrainMaterialIdUniqueIndex:
	var index: ContinuumTerrainMaterialIdUniqueIndex = ContinuumTerrainMaterialIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> ContinuumTerrainMaterial:
	return _cache.get(col_val, null)
