# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumConfigIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, ContinuumConfig] = {}

func _init() -> void:
	set_meta("table_name", "config")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> ContinuumConfigIdUniqueIndex:
	var index: ContinuumConfigIdUniqueIndex = ContinuumConfigIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> ContinuumConfig:
	return _cache.get(col_val, null)
