# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumAlertTable extends _ModuleTable

var id: ContinuumAlertIdUniqueIndex
var code: ContinuumAlertCodeUniqueIndex

func _init() -> void:
	set_meta("table_name", "alert")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumAlert")

static func create(p_local_db: LocalDatabase) -> ContinuumAlertTable:
	var table: ContinuumAlertTable = ContinuumAlertTable.new()
	table._db = p_local_db
	table.id = ContinuumAlertIdUniqueIndex.create(p_local_db)
	table.code = ContinuumAlertCodeUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumAlert]:
	var rows: Array = super()
	var typed_array: Array[ContinuumAlert] = []
	typed_array.assign(rows)
	return typed_array
