# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumColonyIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, ContinuumColony] = {}

func _init() -> void:
	set_meta("table_name", "colony")
	set_meta("field_name", "id")

static func create(p_local_db: LocalDatabase) -> ContinuumColonyIdUniqueIndex:
	var index: ContinuumColonyIdUniqueIndex = ContinuumColonyIdUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: int) -> ContinuumColony:
	return _cache.get(col_val, null)
