# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumMyRoleIdentityUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, ContinuumMembership] = {}

func _init() -> void:
	set_meta("table_name", "my_role")
	set_meta("field_name", "identity")

static func create(p_local_db: LocalDatabase) -> ContinuumMyRoleIdentityUniqueIndex:
	var index: ContinuumMyRoleIdentityUniqueIndex = ContinuumMyRoleIdentityUniqueIndex.new()
	index._connect_cache_to_db(index._cache, p_local_db)
	return index

func find(col_val: PackedByteArray) -> ContinuumMembership:
	return _cache.get(col_val, null)
