# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumEventLogTable extends _ModuleTable

var id: ContinuumEventLogIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "event_log")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumEventLog")

static func create(p_local_db: LocalDatabase) -> ContinuumEventLogTable:
	var table: ContinuumEventLogTable = ContinuumEventLogTable.new()
	table._db = p_local_db
	table.id = ContinuumEventLogIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumEventLog]:
	var rows: Array = super()
	var typed_array: Array[ContinuumEventLog] = []
	typed_array.assign(rows)
	return typed_array
