# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumWorldGenerationTable extends _ModuleTable

var id: ContinuumWorldGenerationIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "world_generation")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumWorldGeneration")

static func create(p_local_db: LocalDatabase) -> ContinuumWorldGenerationTable:
	var table: ContinuumWorldGenerationTable = ContinuumWorldGenerationTable.new()
	table._db = p_local_db
	table.id = ContinuumWorldGenerationIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumWorldGeneration]:
	var rows: Array = super()
	var typed_array: Array[ContinuumWorldGeneration] = []
	typed_array.assign(rows)
	return typed_array
