# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumWorkOrderTable extends _ModuleTable

var id: ContinuumWorkOrderIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "work_order")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumWorkOrder")

static func create(p_local_db: LocalDatabase) -> ContinuumWorkOrderTable:
	var table: ContinuumWorkOrderTable = ContinuumWorkOrderTable.new()
	table._db = p_local_db
	table.id = ContinuumWorkOrderIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumWorkOrder]:
	var rows: Array = super()
	var typed_array: Array[ContinuumWorkOrder] = []
	typed_array.assign(rows)
	return typed_array
