# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumProductionPolicyTable extends _ModuleTable

var resource: ContinuumProductionPolicyResourceUniqueIndex

func _init() -> void:
	set_meta("table_name", "production_policy")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumProductionPolicy")

static func create(p_local_db: LocalDatabase) -> ContinuumProductionPolicyTable:
	var table: ContinuumProductionPolicyTable = ContinuumProductionPolicyTable.new()
	table._db = p_local_db
	table.resource = ContinuumProductionPolicyResourceUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumProductionPolicy]:
	var rows: Array = super()
	var typed_array: Array[ContinuumProductionPolicy] = []
	typed_array.assign(rows)
	return typed_array
