# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTerrainChunkTable extends _ModuleTable

var id: ContinuumTerrainChunkIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "terrain_chunk")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumTerrainChunk")

static func create(p_local_db: LocalDatabase) -> ContinuumTerrainChunkTable:
	var table: ContinuumTerrainChunkTable = ContinuumTerrainChunkTable.new()
	table._db = p_local_db
	table.id = ContinuumTerrainChunkIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumTerrainChunk]:
	var rows: Array = super()
	var typed_array: Array[ContinuumTerrainChunk] = []
	typed_array.assign(rows)
	return typed_array
