# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumColonyTable extends _ModuleTable

var id: ContinuumColonyIdUniqueIndex

func _init() -> void:
	set_meta("table_name", "colony")
	set_meta("is_event", "false")
	set_meta("type", "ContinuumColony")

static func create(p_local_db: LocalDatabase) -> ContinuumColonyTable:
	var table: ContinuumColonyTable = ContinuumColonyTable.new()
	table._db = p_local_db
	table.id = ContinuumColonyIdUniqueIndex.create(p_local_db)
	return table

func iter() -> Array[ContinuumColony]:
	var rows: Array = super()
	var typed_array: Array[ContinuumColony] = []
	typed_array.assign(rows)
	return typed_array
