# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumWorkType extends RustEnum

enum Options {
	none,
	logging,
	mining,
	hunting,
	hauling,
	farming,
}

const enum_options: Array[StringName] = ['', '', '', '', '', '']
const bsatn_enum_type: StringName = &'ContinuumWorkType'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'none'
		1: return &'logging'
		2: return &'mining'
		3: return &'hunting'
		4: return &'hauling'
		5: return &'farming'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumWorkType:
	var result : ContinuumWorkType = ContinuumWorkType.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_none() -> ContinuumWorkType:
	return create(Options.none)

static func create_logging() -> ContinuumWorkType:
	return create(Options.logging)

static func create_mining() -> ContinuumWorkType:
	return create(Options.mining)

static func create_hunting() -> ContinuumWorkType:
	return create(Options.hunting)

static func create_hauling() -> ContinuumWorkType:
	return create(Options.hauling)

static func create_farming() -> ContinuumWorkType:
	return create(Options.farming)
