# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumEventLog extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['event_log']

@export var id: int
@export var game_seconds: float
@export var day: int
@export var hour: int
@export var minute: int
@export var severity: ContinuumSeverity
@export var message: String
@export var at: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"game_seconds": "F64",
	"day": "U32",
	"hour": "U32",
	"minute": "U32",
	"severity": "ContinuumSeverity",
	"message": "String",
	"at": "__timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. game_seconds: float[br]
## 3. day: int[br]
## 4. hour: int[br]
## 5. minute: int[br]
## 6. severity: ContinuumSeverity[br]
## 7. message: String[br]
## 8. at: int[br]
static func create(p_id: int, p_game_seconds: float, p_day: int, p_hour: int, p_minute: int, p_severity: ContinuumSeverity, p_message: String, p_at: int) -> ContinuumEventLog:
	var result: ContinuumEventLog = ContinuumEventLog.new()
	result.id = p_id
	result.game_seconds = p_game_seconds
	result.day = p_day
	result.hour = p_hour
	result.minute = p_minute
	result.severity = p_severity
	result.message = p_message
	result.at = p_at
	return result
