# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumTerrain extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['terrain']

@export var tile_id: int
@export var soil_fertility: float
@export var forest_density: float
@export var moisture: float

#BSATN metadata
const primary_key: StringName = &'tile_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"tile_id": "U32",
	"soil_fertility": "F32",
	"forest_density": "F32",
	"moisture": "F32"
}

## 1. tile_id: int[br]
## 2. soil_fertility: float[br]
## 3. forest_density: float[br]
## 4. moisture: float[br]
static func create(p_tile_id: int, p_soil_fertility: float, p_forest_density: float, p_moisture: float) -> ContinuumTerrain:
	var result: ContinuumTerrain = ContinuumTerrain.new()
	result.tile_id = p_tile_id
	result.soil_fertility = p_soil_fertility
	result.forest_density = p_forest_density
	result.moisture = p_moisture
	return result
