# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumTerrainOverrideAllocator extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = []

@export var id: int
@export var next_id: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"next_id": "U64"
}

## 1. id: int[br]
## 2. next_id: int[br]
static func create(p_id: int, p_next_id: int) -> ContinuumTerrainOverrideAllocator:
	var result: ContinuumTerrainOverrideAllocator = ContinuumTerrainOverrideAllocator.new()
	result.id = p_id
	result.next_id = p_next_id
	return result
