# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumTileKind extends RustEnum

enum Options {
	empty,
	food,
	sleep,
	work,
	recreation,
}

const enum_options: Array[StringName] = ['', '', '', '', '']
const bsatn_enum_type: StringName = &'ContinuumTileKind'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'empty'
		1: return &'food'
		2: return &'sleep'
		3: return &'work'
		4: return &'recreation'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumTileKind:
	var result : ContinuumTileKind = ContinuumTileKind.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_empty() -> ContinuumTileKind:
	return create(Options.empty)

static func create_food() -> ContinuumTileKind:
	return create(Options.food)

static func create_sleep() -> ContinuumTileKind:
	return create(Options.sleep)

static func create_work() -> ContinuumTileKind:
	return create(Options.work)

static func create_recreation() -> ContinuumTileKind:
	return create(Options.recreation)

