# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumMiningCell extends Resource

const module_name : String = "Continuum"
const table_names: Array[String] = []

@export var x: int
@export var y: int
@export var z: int
@export var material: int
@export var progress: float

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"x": "I32",
	"y": "I32",
	"z": "I32",
	"material": "U16",
	"progress": "F32"
}

## 1. x: int[br]
## 2. y: int[br]
## 3. z: int[br]
## 4. material: int[br]
## 5. progress: float[br]
static func create(p_x: int, p_y: int, p_z: int, p_material: int, p_progress: float) -> ContinuumMiningCell:
	var result: ContinuumMiningCell = ContinuumMiningCell.new()
	result.x = p_x
	result.y = p_y
	result.z = p_z
	result.material = p_material
	result.progress = p_progress
	return result
