# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumHaulRole extends RustEnum

enum Options {
	both,
	producer,
	hauler,
}

const enum_options: Array[StringName] = ['', '', '']
const bsatn_enum_type: StringName = &'ContinuumHaulRole'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'both'
		1: return &'producer'
		2: return &'hauler'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumHaulRole:
	var result : ContinuumHaulRole = ContinuumHaulRole.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_both() -> ContinuumHaulRole:
	return create(Options.both)

static func create_producer() -> ContinuumHaulRole:
	return create(Options.producer)

static func create_hauler() -> ContinuumHaulRole:
	return create(Options.hauler)
