# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumSpeedControl extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['speed_control']

@export var id: int
@export var cooldown_seconds: int
@export var last_changed_at: Option

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"cooldown_seconds": "U32",
	"last_changed_at": "opt___timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. cooldown_seconds: int[br]
## 3. last_changed_at: Option[br]
static func create(p_id: int, p_cooldown_seconds: int, p_last_changed_at: Option) -> ContinuumSpeedControl:
	var result: ContinuumSpeedControl = ContinuumSpeedControl.new()
	result.id = p_id
	result.cooldown_seconds = p_cooldown_seconds
	result.last_changed_at = p_last_changed_at
	return result
