# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumActivity extends RustEnum

enum Options {
	idle,
	travelling,
	working,
	hauling,
	eating,
	sleeping,
	recreating,
}

const enum_options: Array[StringName] = ['', '', '', '', '', '', '']
const bsatn_enum_type: StringName = &'ContinuumActivity'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'idle'
		1: return &'travelling'
		2: return &'working'
		3: return &'hauling'
		4: return &'eating'
		5: return &'sleeping'
		6: return &'recreating'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumActivity:
	var result : ContinuumActivity = ContinuumActivity.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_idle() -> ContinuumActivity:
	return create(Options.idle)

static func create_travelling() -> ContinuumActivity:
	return create(Options.travelling)

static func create_working() -> ContinuumActivity:
	return create(Options.working)

static func create_hauling() -> ContinuumActivity:
	return create(Options.hauling)

static func create_eating() -> ContinuumActivity:
	return create(Options.eating)

static func create_sleeping() -> ContinuumActivity:
	return create(Options.sleeping)

static func create_recreating() -> ContinuumActivity:
	return create(Options.recreating)

