# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumProductionPolicy extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['production_policy']

@export var resource: ContinuumResourceKind
@export var target: float

#BSATN metadata
const primary_key: StringName = &'resource'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"resource": "ContinuumResourceKind",
	"target": "F32"
}

## 1. resource: ContinuumResourceKind[br]
## 2. target: float[br]
static func create(p_resource: ContinuumResourceKind, p_target: float) -> ContinuumProductionPolicy:
	var result: ContinuumProductionPolicy = ContinuumProductionPolicy.new()
	result.resource = p_resource
	result.target = p_target
	return result
