# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumGenerationPhase extends RustEnum

enum Options {
	preparing,
	terrain,
	overview,
	validating,
	founding,
	ready,
	failed,
}

const enum_options: Array[StringName] = ['', '', '', '', '', '', '']
const bsatn_enum_type: StringName = &'ContinuumGenerationPhase'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'preparing'
		1: return &'terrain'
		2: return &'overview'
		3: return &'validating'
		4: return &'founding'
		5: return &'ready'
		6: return &'failed'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumGenerationPhase:
	var result : ContinuumGenerationPhase = ContinuumGenerationPhase.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_preparing() -> ContinuumGenerationPhase:
	return create(Options.preparing)

static func create_terrain() -> ContinuumGenerationPhase:
	return create(Options.terrain)

static func create_overview() -> ContinuumGenerationPhase:
	return create(Options.overview)

static func create_validating() -> ContinuumGenerationPhase:
	return create(Options.validating)

static func create_founding() -> ContinuumGenerationPhase:
	return create(Options.founding)

static func create_ready() -> ContinuumGenerationPhase:
	return create(Options.ready)

static func create_failed() -> ContinuumGenerationPhase:
	return create(Options.failed)
