# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumResourceKind extends RustEnum

enum Options {
	food,
	wood,
	stone,
	meat,
}

const enum_options: Array[StringName] = ['', '', '', '']
const bsatn_enum_type: StringName = &'ContinuumResourceKind'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'food'
		1: return &'wood'
		2: return &'stone'
		3: return &'meat'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumResourceKind:
	var result : ContinuumResourceKind = ContinuumResourceKind.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_food() -> ContinuumResourceKind:
	return create(Options.food)

static func create_wood() -> ContinuumResourceKind:
	return create(Options.wood)

static func create_stone() -> ContinuumResourceKind:
	return create(Options.stone)

static func create_meat() -> ContinuumResourceKind:
	return create(Options.meat)

