# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumItemStack extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['item_stack']

@export var id: int
@export var tile_id: int
@export var x: int
@export var y: int
@export var kind: ContinuumResourceKind
@export var amount: float

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"tile_id": "U32",
	"x": "I32",
	"y": "I32",
	"kind": "ContinuumResourceKind",
	"amount": "F32"
}

## 1. id: int[br]
## 2. tile_id: int[br]
## 3. x: int[br]
## 4. y: int[br]
## 5. kind: ContinuumResourceKind[br]
## 6. amount: float[br]
static func create(p_id: int, p_tile_id: int, p_x: int, p_y: int, p_kind: ContinuumResourceKind, p_amount: float) -> ContinuumItemStack:
	var result: ContinuumItemStack = ContinuumItemStack.new()
	result.id = p_id
	result.tile_id = p_tile_id
	result.x = p_x
	result.y = p_y
	result.kind = p_kind
	result.amount = p_amount
	return result
