# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumTerrainOverviewChunk extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['terrain_overview_chunk']

@export var id: int
@export var generation_id: int
@export var revision: int
@export var lod: int
@export var cut_z: int
@export var chunk_x: int
@export var chunk_y: int
@export var surface_z: Array[int]
@export var material: Array[int]
@export var soil_fertility: PackedByteArray
@export var forest_density: PackedByteArray
@export var moisture: PackedByteArray

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"generation_id": "U64",
	"revision": "U32",
	"lod": "U8",
	"cut_z": "I32",
	"chunk_x": "I32",
	"chunk_y": "I32",
	"surface_z": "vec_I16",
	"material": "vec_U16",
	"soil_fertility": "vec_U8",
	"forest_density": "vec_U8",
	"moisture": "vec_U8"
}

## 1. id: int[br]
## 2. generation_id: int[br]
## 3. revision: int[br]
## 4. lod: int[br]
## 5. cut_z: int[br]
## 6. chunk_x: int[br]
## 7. chunk_y: int[br]
## 8. surface_z: Array[int][br]
## 9. material: Array[int][br]
## 10. soil_fertility: PackedByteArray[br]
## 11. forest_density: PackedByteArray[br]
## 12. moisture: PackedByteArray[br]
static func create(p_id: int, p_generation_id: int, p_revision: int, p_lod: int, p_cut_z: int, p_chunk_x: int, p_chunk_y: int, p_surface_z: Array[int], p_material: Array[int], p_soil_fertility: PackedByteArray, p_forest_density: PackedByteArray, p_moisture: PackedByteArray) -> ContinuumTerrainOverviewChunk:
	var result: ContinuumTerrainOverviewChunk = ContinuumTerrainOverviewChunk.new()
	result.id = p_id
	result.generation_id = p_generation_id
	result.revision = p_revision
	result.lod = p_lod
	result.cut_z = p_cut_z
	result.chunk_x = p_chunk_x
	result.chunk_y = p_chunk_y
	result.surface_z = p_surface_z
	result.material = p_material
	result.soil_fertility = p_soil_fertility
	result.forest_density = p_forest_density
	result.moisture = p_moisture
	return result
