# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumWorldSeed extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['world_seed']

@export var id: int
@export var seed: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"seed": "U64"
}

## 1. id: int[br]
## 2. seed: int[br]
static func create(p_id: int, p_seed: int) -> ContinuumWorldSeed:
	var result: ContinuumWorldSeed = ContinuumWorldSeed.new()
	result.id = p_id
	result.seed = p_seed
	return result
