# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumBuilding extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['building']

@export var id: int
@export var kind: ContinuumBuildingKind
@export var x: int
@export var y: int
@export var z: int
@export var width: int
@export var depth: int
@export var clearance_height: int
@export var wood_cost: float

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"kind": "ContinuumBuildingKind",
	"x": "I32",
	"y": "I32",
	"z": "I32",
	"width": "U16",
	"depth": "U16",
	"clearance_height": "U16",
	"wood_cost": "F32"
}

## 1. id: int[br]
## 2. kind: ContinuumBuildingKind[br]
## 3. x: int[br]
## 4. y: int[br]
## 5. z: int[br]
## 6. width: int[br]
## 7. depth: int[br]
## 8. clearance_height: int[br]
## 9. wood_cost: float[br]
static func create(p_id: int, p_kind: ContinuumBuildingKind, p_x: int, p_y: int, p_z: int, p_width: int, p_depth: int, p_clearance_height: int, p_wood_cost: float) -> ContinuumBuilding:
	var result: ContinuumBuilding = ContinuumBuilding.new()
	result.id = p_id
	result.kind = p_kind
	result.x = p_x
	result.y = p_y
	result.z = p_z
	result.width = p_width
	result.depth = p_depth
	result.clearance_height = p_clearance_height
	result.wood_cost = p_wood_cost
	return result
