# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumMealPolicy extends RustEnum

enum Options {
	normal,
	rationed,
}

const enum_options: Array[StringName] = ['', '']
const bsatn_enum_type: StringName = &'ContinuumMealPolicy'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'normal'
		1: return &'rationed'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumMealPolicy:
	var result : ContinuumMealPolicy = ContinuumMealPolicy.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_normal() -> ContinuumMealPolicy:
	return create(Options.normal)

static func create_rationed() -> ContinuumMealPolicy:
	return create(Options.rationed)

