# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumSeverity extends RustEnum

enum Options {
	info,
	warning,
	critical,
}

const enum_options: Array[StringName] = ['', '', '']
const bsatn_enum_type: StringName = &'ContinuumSeverity'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'info'
		1: return &'warning'
		2: return &'critical'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumSeverity:
	var result : ContinuumSeverity = ContinuumSeverity.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_info() -> ContinuumSeverity:
	return create(Options.info)

static func create_warning() -> ContinuumSeverity:
	return create(Options.warning)

static func create_critical() -> ContinuumSeverity:
	return create(Options.critical)

