# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumTerrainChunk extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['terrain_chunk']

@export var id: int
@export var chunk_x: int
@export var chunk_y: int
@export var chunk_z: int
@export var materials: Array[int]
@export var revision: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"chunk_x": "I32",
	"chunk_y": "I32",
	"chunk_z": "I32",
	"materials": "vec_U16",
	"revision": "U32"
}

## 1. id: int[br]
## 2. chunk_x: int[br]
## 3. chunk_y: int[br]
## 4. chunk_z: int[br]
## 5. materials: Array[int][br]
## 6. revision: int[br]
static func create(p_id: int, p_chunk_x: int, p_chunk_y: int, p_chunk_z: int, p_materials: Array[int], p_revision: int) -> ContinuumTerrainChunk:
	var result: ContinuumTerrainChunk = ContinuumTerrainChunk.new()
	result.id = p_id
	result.chunk_x = p_chunk_x
	result.chunk_y = p_chunk_y
	result.chunk_z = p_chunk_z
	result.materials = p_materials
	result.revision = p_revision
	return result
