# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumBuildingThermalProperty extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['building_thermal_property']

@export var building_id: int
@export var thermal_resistance_m_2_k_per_w: float

#BSATN metadata
const primary_key: StringName = &'building_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"building_id": "U64",
	"thermal_resistance_m_2_k_per_w": "F32"
}

## 1. building_id: int[br]
## 2. thermal_resistance_m_2_k_per_w: float[br]
static func create(p_building_id: int, p_thermal_resistance_m_2_k_per_w: float) -> ContinuumBuildingThermalProperty:
	var result: ContinuumBuildingThermalProperty = ContinuumBuildingThermalProperty.new()
	result.building_id = p_building_id
	result.thermal_resistance_m_2_k_per_w = p_thermal_resistance_m_2_k_per_w
	return result
