# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumTerrainMaterial extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['terrain_material']

@export var id: int
@export var name: String
@export var density: float
@export var strength: float
@export var thermal_conductivity: float
@export var specific_heat_capacity: float
@export var opaque: bool

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U16",
	"name": "String",
	"density": "F32",
	"strength": "F32",
	"thermal_conductivity": "F32",
	"specific_heat_capacity": "F32",
	"opaque": "Bool"
}

## 1. id: int[br]
## 2. name: String[br]
## 3. density: float[br]
## 4. strength: float[br]
## 5. thermal_conductivity: float[br]
## 6. specific_heat_capacity: float[br]
## 7. opaque: bool[br]
static func create(p_id: int, p_name: String, p_density: float, p_strength: float, p_thermal_conductivity: float, p_specific_heat_capacity: float, p_opaque: bool) -> ContinuumTerrainMaterial:
	var result: ContinuumTerrainMaterial = ContinuumTerrainMaterial.new()
	result.id = p_id
	result.name = p_name
	result.density = p_density
	result.strength = p_strength
	result.thermal_conductivity = p_thermal_conductivity
	result.specific_heat_capacity = p_specific_heat_capacity
	result.opaque = p_opaque
	return result
