# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumOwnRole extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['my_role']

@export var role: ContinuumRole

#BSATN metadata
const primary_key: StringName = &''
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"role": "ContinuumRole"
}

## 1. role: ContinuumRole[br]
static func create(p_role: ContinuumRole) -> ContinuumOwnRole:
	var result: ContinuumOwnRole = ContinuumOwnRole.new()
	result.role = p_role
	return result
