# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumExcavationJobs extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = []

@export var id: int
@export var cells: Array[ContinuumMiningCell]

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"cells": "vec_ContinuumMiningCell"
}

## 1. id: int[br]
## 2. cells: Array[ContinuumMiningCell][br]
static func create(p_id: int, p_cells: Array[ContinuumMiningCell]) -> ContinuumExcavationJobs:
	var result: ContinuumExcavationJobs = ContinuumExcavationJobs.new()
	result.id = p_id
	result.cells = p_cells
	return result
