# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumGoal extends RustEnum

enum Options {
	nothing,
	eat,
	sleep,
	recreate,
	work,
	haul,
}

const enum_options: Array[StringName] = ['', '', '', '', '', '']
const bsatn_enum_type: StringName = &'ContinuumGoal'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'nothing'
		1: return &'eat'
		2: return &'sleep'
		3: return &'recreate'
		4: return &'work'
		5: return &'haul'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumGoal:
	var result : ContinuumGoal = ContinuumGoal.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_nothing() -> ContinuumGoal:
	return create(Options.nothing)

static func create_eat() -> ContinuumGoal:
	return create(Options.eat)

static func create_sleep() -> ContinuumGoal:
	return create(Options.sleep)

static func create_recreate() -> ContinuumGoal:
	return create(Options.recreate)

static func create_work() -> ContinuumGoal:
	return create(Options.work)

static func create_haul() -> ContinuumGoal:
	return create(Options.haul)

