# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumWorldGenerationControl extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = []

@export var id: int
@export var generation_id: int
@export var expected_task_id: int
@export var resume_phase: ContinuumGenerationPhase
@export var requested_time_scale: float

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"generation_id": "U64",
	"expected_task_id": "U64",
	"resume_phase": "ContinuumGenerationPhase",
	"requested_time_scale": "F64"
}

## 1. id: int[br]
## 2. generation_id: int[br]
## 3. expected_task_id: int[br]
## 4. resume_phase: ContinuumGenerationPhase[br]
## 5. requested_time_scale: float[br]
static func create(p_id: int, p_generation_id: int, p_expected_task_id: int, p_resume_phase: ContinuumGenerationPhase, p_requested_time_scale: float) -> ContinuumWorldGenerationControl:
	var result: ContinuumWorldGenerationControl = ContinuumWorldGenerationControl.new()
	result.id = p_id
	result.generation_id = p_generation_id
	result.expected_task_id = p_expected_task_id
	result.resume_phase = p_resume_phase
	result.requested_time_scale = p_requested_time_scale
	return result
