# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumRole extends RustEnum

enum Options {
	admin,
	operator,
}

const enum_options: Array[StringName] = ['', '']
const bsatn_enum_type: StringName = &'ContinuumRole'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'admin'
		1: return &'operator'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumRole:
	var result : ContinuumRole = ContinuumRole.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_admin() -> ContinuumRole:
	return create(Options.admin)

static func create_operator() -> ContinuumRole:
	return create(Options.operator)
