# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumColony extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['colony']

@export var id: int
@export var food: float
@export var food_capacity: float
@export var avg_mood: float
@export var avg_productivity: float
@export var smoothed_mood: float
@export var smoothed_productivity: float
@export var population: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"food": "F32",
	"food_capacity": "F32",
	"avg_mood": "F32",
	"avg_productivity": "F32",
	"smoothed_mood": "F32",
	"smoothed_productivity": "F32",
	"population": "U32"
}

## 1. id: int[br]
## 2. food: float[br]
## 3. food_capacity: float[br]
## 4. avg_mood: float[br]
## 5. avg_productivity: float[br]
## 6. smoothed_mood: float[br]
## 7. smoothed_productivity: float[br]
## 8. population: int[br]
static func create(p_id: int, p_food: float, p_food_capacity: float, p_avg_mood: float, p_avg_productivity: float, p_smoothed_mood: float, p_smoothed_productivity: float, p_population: int) -> ContinuumColony:
	var result: ContinuumColony = ContinuumColony.new()
	result.id = p_id
	result.food = p_food
	result.food_capacity = p_food_capacity
	result.avg_mood = p_avg_mood
	result.avg_productivity = p_avg_productivity
	result.smoothed_mood = p_smoothed_mood
	result.smoothed_productivity = p_smoothed_productivity
	result.population = p_population
	return result
