# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumBuildingKind extends RustEnum

enum Options {
	insulatedRoom,
}

const enum_options: Array[StringName] = ['']
const bsatn_enum_type: StringName = &'ContinuumBuildingKind'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'insulatedRoom'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumBuildingKind:
	var result : ContinuumBuildingKind = ContinuumBuildingKind.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_insulated_room() -> ContinuumBuildingKind:
	return create(Options.insulatedRoom)
