# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumWorldGenerationTask extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = []

@export var scheduled_id: int
@export var scheduled_at: int
@export var generation_id: int

#BSATN metadata
const primary_key: StringName = &'scheduled_id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"scheduled_id": "U64",
	"scheduled_at": "scheduled_at",
	"generation_id": "U64"
}

## 1. scheduled_id: int[br]
## 2. scheduled_at: int[br]
## 3. generation_id: int[br]
static func create(p_scheduled_id: int, p_scheduled_at: int, p_generation_id: int) -> ContinuumWorldGenerationTask:
	var result: ContinuumWorldGenerationTask = ContinuumWorldGenerationTask.new()
	result.scheduled_id = p_scheduled_id
	result.scheduled_at = p_scheduled_at
	result.generation_id = p_generation_id
	return result
