# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumWorldGeneration extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['world_generation']

@export var id: int
@export var generation_id: int
@export var generator_version: int
@export var storage_version: int
@export var seed: int
@export var width: int
@export var height: int
@export var min_z: int
@export var max_z: int
@export var starter_x: int
@export var starter_y: int
@export var phase: ContinuumGenerationPhase
@export var completed_chunks: int
@export var total_chunks: int
@export var completed_units: int
@export var total_units: int
@export var ready: bool
@export var error: String

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"generation_id": "U64",
	"generator_version": "U32",
	"storage_version": "U32",
	"seed": "U64",
	"width": "I32",
	"height": "I32",
	"min_z": "I32",
	"max_z": "I32",
	"starter_x": "I32",
	"starter_y": "I32",
	"phase": "ContinuumGenerationPhase",
	"completed_chunks": "U32",
	"total_chunks": "U32",
	"completed_units": "U64",
	"total_units": "U64",
	"ready": "Bool",
	"error": "String"
}

## 1. id: int[br]
## 2. generation_id: int[br]
## 3. generator_version: int[br]
## 4. storage_version: int[br]
## 5. seed: int[br]
## 6. width: int[br]
## 7. height: int[br]
## 8. min_z: int[br]
## 9. max_z: int[br]
## 10. starter_x: int[br]
## 11. starter_y: int[br]
## 12. phase: ContinuumGenerationPhase[br]
## 13. completed_chunks: int[br]
## 14. total_chunks: int[br]
## 15. completed_units: int[br]
## 16. total_units: int[br]
## 17. ready: bool[br]
## 18. error: String[br]
static func create(p_id: int, p_generation_id: int, p_generator_version: int, p_storage_version: int, p_seed: int, p_width: int, p_height: int, p_min_z: int, p_max_z: int, p_starter_x: int, p_starter_y: int, p_phase: ContinuumGenerationPhase, p_completed_chunks: int, p_total_chunks: int, p_completed_units: int, p_total_units: int, p_ready: bool, p_error: String) -> ContinuumWorldGeneration:
	var result: ContinuumWorldGeneration = ContinuumWorldGeneration.new()
	result.id = p_id
	result.generation_id = p_generation_id
	result.generator_version = p_generator_version
	result.storage_version = p_storage_version
	result.seed = p_seed
	result.width = p_width
	result.height = p_height
	result.min_z = p_min_z
	result.max_z = p_max_z
	result.starter_x = p_starter_x
	result.starter_y = p_starter_y
	result.phase = p_phase
	result.completed_chunks = p_completed_chunks
	result.total_chunks = p_total_chunks
	result.completed_units = p_completed_units
	result.total_units = p_total_units
	result.ready = p_ready
	result.error = p_error
	return result
