# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumExcavationDesignation extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['excavation_designation']

@export var id: int
@export var x_0: int
@export var y_0: int
@export var x_1: int
@export var y_1: int
@export var bottom_z: int
@export var height: int
@export var priority: int
@export var enabled: bool
@export var total_cells: int
@export var completed_cells: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"x_0": "I32",
	"y_0": "I32",
	"x_1": "I32",
	"y_1": "I32",
	"bottom_z": "I32",
	"height": "U16",
	"priority": "U8",
	"enabled": "Bool",
	"total_cells": "U32",
	"completed_cells": "U32"
}

## 1. id: int[br]
## 2. x_0: int[br]
## 3. y_0: int[br]
## 4. x_1: int[br]
## 5. y_1: int[br]
## 6. bottom_z: int[br]
## 7. height: int[br]
## 8. priority: int[br]
## 9. enabled: bool[br]
## 10. total_cells: int[br]
## 11. completed_cells: int[br]
static func create(p_id: int, p_x_0: int, p_y_0: int, p_x_1: int, p_y_1: int, p_bottom_z: int, p_height: int, p_priority: int, p_enabled: bool, p_total_cells: int, p_completed_cells: int) -> ContinuumExcavationDesignation:
	var result: ContinuumExcavationDesignation = ContinuumExcavationDesignation.new()
	result.id = p_id
	result.x_0 = p_x_0
	result.y_0 = p_y_0
	result.x_1 = p_x_1
	result.y_1 = p_y_1
	result.bottom_z = p_bottom_z
	result.height = p_height
	result.priority = p_priority
	result.enabled = p_enabled
	result.total_cells = p_total_cells
	result.completed_cells = p_completed_cells
	return result
