# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumColonist extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['colonist']

@export var id: int
@export var name: String
@export var x: int
@export var y: int
@export var move_progress: float
@export var target_x: int
@export var target_y: int
@export var activity: ContinuumActivity
@export var work: ContinuumWorkType
@export var goal: ContinuumGoal
@export var hunger: float
@export var fatigue: float
@export var recreation: float
@export var mood: float
@export var productivity: float
@export var sleep_hours: float
@export var last_sleep_quality: float

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"name": "String",
	"x": "I32",
	"y": "I32",
	"move_progress": "F32",
	"target_x": "I32",
	"target_y": "I32",
	"activity": "ContinuumActivity",
	"work": "ContinuumWorkType",
	"goal": "ContinuumGoal",
	"hunger": "F32",
	"fatigue": "F32",
	"recreation": "F32",
	"mood": "F32",
	"productivity": "F32",
	"sleep_hours": "F32",
	"last_sleep_quality": "F32"
}

## 1. id: int[br]
## 2. name: String[br]
## 3. x: int[br]
## 4. y: int[br]
## 5. move_progress: float[br]
## 6. target_x: int[br]
## 7. target_y: int[br]
## 8. activity: ContinuumActivity[br]
## 9. work: ContinuumWorkType[br]
## 10. goal: ContinuumGoal[br]
## 11. hunger: float[br]
## 12. fatigue: float[br]
## 13. recreation: float[br]
## 14. mood: float[br]
## 15. productivity: float[br]
## 16. sleep_hours: float[br]
## 17. last_sleep_quality: float[br]
static func create(p_id: int, p_name: String, p_x: int, p_y: int, p_move_progress: float, p_target_x: int, p_target_y: int, p_activity: ContinuumActivity, p_work: ContinuumWorkType, p_goal: ContinuumGoal, p_hunger: float, p_fatigue: float, p_recreation: float, p_mood: float, p_productivity: float, p_sleep_hours: float, p_last_sleep_quality: float) -> ContinuumColonist:
	var result: ContinuumColonist = ContinuumColonist.new()
	result.id = p_id
	result.name = p_name
	result.x = p_x
	result.y = p_y
	result.move_progress = p_move_progress
	result.target_x = p_target_x
	result.target_y = p_target_y
	result.activity = p_activity
	result.work = p_work
	result.goal = p_goal
	result.hunger = p_hunger
	result.fatigue = p_fatigue
	result.recreation = p_recreation
	result.mood = p_mood
	result.productivity = p_productivity
	result.sleep_hours = p_sleep_hours
	result.last_sleep_quality = p_last_sleep_quality
	return result
