# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumWorkOrder extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['work_order']

@export var id: int
@export var tile_id: int
@export var work: ContinuumWorkType
@export var priority: int
@export var enabled: bool

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"tile_id": "U32",
	"work": "ContinuumWorkType",
	"priority": "U8",
	"enabled": "Bool"
}

## 1. id: int[br]
## 2. tile_id: int[br]
## 3. work: ContinuumWorkType[br]
## 4. priority: int[br]
## 5. enabled: bool[br]
static func create(p_id: int, p_tile_id: int, p_work: ContinuumWorkType, p_priority: int, p_enabled: bool) -> ContinuumWorkOrder:
	var result: ContinuumWorkOrder = ContinuumWorkOrder.new()
	result.id = p_id
	result.tile_id = p_tile_id
	result.work = p_work
	result.priority = p_priority
	result.enabled = p_enabled
	return result
