# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumTerrainColumnChunk extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['terrain_column_chunk']

@export var id: int
@export var chunk_x: int
@export var chunk_y: int
@export var generation_id: int
@export var revision: int
@export var base_z: Array[int]
@export var soil_depth: PackedByteArray
@export var soil_fertility: PackedByteArray
@export var forest_density: PackedByteArray
@export var moisture: PackedByteArray

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"chunk_x": "I32",
	"chunk_y": "I32",
	"generation_id": "U64",
	"revision": "U32",
	"base_z": "vec_I16",
	"soil_depth": "vec_U8",
	"soil_fertility": "vec_U8",
	"forest_density": "vec_U8",
	"moisture": "vec_U8"
}

## 1. id: int[br]
## 2. chunk_x: int[br]
## 3. chunk_y: int[br]
## 4. generation_id: int[br]
## 5. revision: int[br]
## 6. base_z: Array[int][br]
## 7. soil_depth: PackedByteArray[br]
## 8. soil_fertility: PackedByteArray[br]
## 9. forest_density: PackedByteArray[br]
## 10. moisture: PackedByteArray[br]
static func create(p_id: int, p_chunk_x: int, p_chunk_y: int, p_generation_id: int, p_revision: int, p_base_z: Array[int], p_soil_depth: PackedByteArray, p_soil_fertility: PackedByteArray, p_forest_density: PackedByteArray, p_moisture: PackedByteArray) -> ContinuumTerrainColumnChunk:
	var result: ContinuumTerrainColumnChunk = ContinuumTerrainColumnChunk.new()
	result.id = p_id
	result.chunk_x = p_chunk_x
	result.chunk_y = p_chunk_y
	result.generation_id = p_generation_id
	result.revision = p_revision
	result.base_z = p_base_z
	result.soil_depth = p_soil_depth
	result.soil_fertility = p_soil_fertility
	result.forest_density = p_forest_density
	result.moisture = p_moisture
	return result
