# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumWorldGeometry extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['world_geometry']

@export var id: int
@export var width: int
@export var height: int
@export var min_z: int
@export var max_z: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U32",
	"width": "I32",
	"height": "I32",
	"min_z": "I32",
	"max_z": "I32"
}

## 1. id: int[br]
## 2. width: int[br]
## 3. height: int[br]
## 4. min_z: int[br]
## 5. max_z: int[br]
static func create(p_id: int, p_width: int, p_height: int, p_min_z: int, p_max_z: int) -> ContinuumWorldGeometry:
	var result: ContinuumWorldGeometry = ContinuumWorldGeometry.new()
	result.id = p_id
	result.width = p_width
	result.height = p_height
	result.min_z = p_min_z
	result.max_z = p_max_z
	return result
