# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumHaulPolicy extends RustEnum

enum Options {
	selfHaul,
	dedicatedHaulers,
}

const enum_options: Array[StringName] = ['', '']
const bsatn_enum_type: StringName = &'ContinuumHaulPolicy'

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'selfHaul'
		1: return &'dedicatedHaulers'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

static func create(p_type: int, p_data: Variant = null) -> ContinuumHaulPolicy:
	var result : ContinuumHaulPolicy = ContinuumHaulPolicy.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_self_haul() -> ContinuumHaulPolicy:
	return create(Options.selfHaul)

static func create_dedicated_haulers() -> ContinuumHaulPolicy:
	return create(Options.dedicatedHaulers)
