# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumMembership extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = []

@export var identity: PackedByteArray
@export var role: ContinuumRole

#BSATN metadata
const primary_key: StringName = &'identity'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"identity": "__identity__",
	"role": "ContinuumRole"
}

## 1. identity: PackedByteArray[br]
## 2. role: ContinuumRole[br]
static func create(p_identity: PackedByteArray, p_role: ContinuumRole) -> ContinuumMembership:
	var result: ContinuumMembership = ContinuumMembership.new()
	result.identity = p_identity
	result.role = p_role
	return result
