# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumAlert extends _ModuleTableType

const module_name : String = "Continuum"
const table_names: Array[String] = ['alert']

@export var id: int
@export var code: String
@export var severity: ContinuumSeverity
@export var message: String
@export var active: bool
@export var acknowledged: bool
@export var raised_game_seconds: float
@export var raised_at: int

#BSATN metadata
const primary_key: StringName = &'id'
const BSATN_TYPES: Dictionary[StringName, StringName] = {
	"id": "U64",
	"code": "String",
	"severity": "ContinuumSeverity",
	"message": "String",
	"active": "Bool",
	"acknowledged": "Bool",
	"raised_game_seconds": "F64",
	"raised_at": "__timestamp_micros_since_unix_epoch__"
}

## 1. id: int[br]
## 2. code: String[br]
## 3. severity: ContinuumSeverity[br]
## 4. message: String[br]
## 5. active: bool[br]
## 6. acknowledged: bool[br]
## 7. raised_game_seconds: float[br]
## 8. raised_at: int[br]
static func create(p_id: int, p_code: String, p_severity: ContinuumSeverity, p_message: String, p_active: bool, p_acknowledged: bool, p_raised_game_seconds: float, p_raised_at: int) -> ContinuumAlert:
	var result: ContinuumAlert = ContinuumAlert.new()
	result.id = p_id
	result.code = p_code
	result.severity = p_severity
	result.message = p_message
	result.active = p_active
	result.acknowledged = p_acknowledged
	result.raised_game_seconds = p_raised_game_seconds
	result.raised_at = p_raised_at
	return result
