# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name ContinuumModuleClient extends SpacetimeDBClient

const Types = preload('res://spacetime_bindings/schema/module_continuum_types.gd')

const Alert = Types.Alert
const Severity = Types.Severity
const Colonist = Types.Colonist
const Activity = Types.Activity
const WorkType = Types.WorkType
const HaulRole = Types.HaulRole
const ResourceKind = Types.ResourceKind
const Goal = Types.Goal
const Colony = Types.Colony
const Config = Types.Config
const HaulPolicy = Types.HaulPolicy
const EventLog = Types.EventLog
const ItemStack = Types.ItemStack
const Role = Types.Role
const TileKind = Types.TileKind
const SpeedControl = Types.SpeedControl
const Tile = Types.Tile
const WorkOrder = Types.WorkOrder


var reducers: ContinuumModuleReducers
var procedures: ContinuumModuleProcedures
var db: ContinuumModuleDb

func _init() -> void:
	set_meta("module_name", "Continuum")
	name = "ContinuumModule"
	reducers = preload('res://spacetime_bindings/schema/module_continuum_reducers.gd').new(self)
	procedures = preload('res://spacetime_bindings/schema/module_continuum_procedures.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_continuum_db.gd').new(p_local_db)
