# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. alert_id: int [br]
func acknowledge_alert(alert_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('acknowledge_alert', [alert_id], [&'U64'])

## 0. tile_id: int [br]
## 1. kind: ContinuumTileKind [br]
func build_facility(tile_id: int, kind: ContinuumTileKind) -> SpacetimeDBReducerCall:
	return _client.call_reducer('build_facility', [tile_id, kind], [&'U32', &'ContinuumTileKind'])

## 0. start_x: int [br]
## 1. start_y: int [br]
## 2. end_x: int [br]
## 3. end_y: int [br]
## 4. kind: ContinuumTileKind [br]
func build_tile_block(start_x: int, start_y: int, end_x: int, end_y: int, kind: ContinuumTileKind) -> SpacetimeDBReducerCall:
	return _client.call_reducer('build_tile_block', [start_x, start_y, end_x, end_y, kind], [&'I32', &'I32', &'I32', &'I32', &'ContinuumTileKind'])

## 0. order_id: int [br]
func remove_work_order(order_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('remove_work_order', [order_id], [&'U64'])


func reset_colony() -> SpacetimeDBReducerCall:
	return _client.call_reducer('reset_colony', [], [])

## 0. start_x: int [br]
## 1. start_y: int [br]
## 2. end_x: int [br]
## 3. end_y: int [br]
## 4. work: ContinuumWorkType [br]
## 5. priority: int [br]
## 6. enabled: bool [br]
func set_block_work_order(start_x: int, start_y: int, end_x: int, end_y: int, work: ContinuumWorkType, priority: int, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_block_work_order', [start_x, start_y, end_x, end_y, work, priority, enabled], [&'I32', &'I32', &'I32', &'I32', &'ContinuumWorkType', &'U8', &'Bool'])

## 0. policy: ContinuumHaulPolicy [br]
func set_haul_policy(policy: ContinuumHaulPolicy) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_haul_policy', [policy], [&'ContinuumHaulPolicy'])

## 0. policy: ContinuumMealPolicy [br]
func set_meal_policy(policy: ContinuumMealPolicy) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_meal_policy', [policy], [&'ContinuumMealPolicy'])

## 0. identity: PackedByteArray [br]
## 1. authorized: bool [br]
func set_operator(identity: PackedByteArray, authorized: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_operator', [identity, authorized], [&'__identity__', &'Bool'])

## 0. cooldown_seconds: int [br]
func set_speed_change_cooldown(cooldown_seconds: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_speed_change_cooldown', [cooldown_seconds], [&'U32'])

## 0. start_x: int [br]
## 1. start_y: int [br]
## 2. end_x: int [br]
## 3. end_y: int [br]
## 4. enabled: bool [br]
func set_tile_block_enabled(start_x: int, start_y: int, end_x: int, end_y: int, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_tile_block_enabled', [start_x, start_y, end_x, end_y, enabled], [&'I32', &'I32', &'I32', &'I32', &'Bool'])

## 0. tile_id: int [br]
## 1. enabled: bool [br]
func set_tile_enabled(tile_id: int, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_tile_enabled', [tile_id, enabled], [&'U32', &'Bool'])

## 0. time_scale: float [br]
func set_time_scale(time_scale: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_time_scale', [time_scale], [&'F64'])

## 0. tile_id: int [br]
## 1. work: ContinuumWorkType [br]
## 2. priority: int [br]
## 3. enabled: bool [br]
func set_work_order(tile_id: int, work: ContinuumWorkType, priority: int, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_work_order', [tile_id, work, priority, enabled], [&'U32', &'ContinuumWorkType', &'U8', &'Bool'])

## 0. kind: ContinuumTileKind [br]
## 1. enabled: bool [br]
func set_zone_enabled(kind: ContinuumTileKind, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_zone_enabled', [kind, enabled], [&'ContinuumTileKind', &'Bool'])

