# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

const Alert = preload('res://spacetime_bindings/schema/types/continuum_alert.gd')
const Severity = preload('res://spacetime_bindings/schema/types/continuum_severity.gd')
const Colonist = preload('res://spacetime_bindings/schema/types/continuum_colonist.gd')
const Activity = preload('res://spacetime_bindings/schema/types/continuum_activity.gd')
const WorkType = preload('res://spacetime_bindings/schema/types/continuum_work_type.gd')
const Goal = preload('res://spacetime_bindings/schema/types/continuum_goal.gd')
const Colony = preload('res://spacetime_bindings/schema/types/continuum_colony.gd')
const Config = preload('res://spacetime_bindings/schema/types/continuum_config.gd')
const EventLog = preload('res://spacetime_bindings/schema/types/continuum_event_log.gd')
const TileKind = preload('res://spacetime_bindings/schema/types/continuum_tile_kind.gd')
const Tile = preload('res://spacetime_bindings/schema/types/continuum_tile.gd')
