# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name ContinuumModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. alert_id: int [br]
func acknowledge_alert(alert_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('acknowledge_alert', [alert_id], [&'U64'])


func reset_colony() -> SpacetimeDBReducerCall:
	return _client.call_reducer('reset_colony', [], [])

## 0. policy: ContinuumHaulPolicy [br]
func set_haul_policy(policy: ContinuumHaulPolicy) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_haul_policy', [policy], [&'ContinuumHaulPolicy'])

## 0. identity: PackedByteArray [br]
## 1. authorized: bool [br]
func set_operator(identity: PackedByteArray, authorized: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_operator', [identity, authorized], [&'__identity__', &'Bool'])

## 0. tile_id: int [br]
## 1. enabled: bool [br]
func set_tile_enabled(tile_id: int, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_tile_enabled', [tile_id, enabled], [&'U32', &'Bool'])

## 0. time_scale: float [br]
func set_time_scale(time_scale: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_time_scale', [time_scale], [&'F64'])

## 0. kind: ContinuumTileKind [br]
## 1. enabled: bool [br]
func set_zone_enabled(kind: ContinuumTileKind, enabled: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_zone_enabled', [kind, enabled], [&'ContinuumTileKind', &'Bool'])

