# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
extends Node
#SpacetimeDB Autoload

var Continuum: ContinuumModuleClient

func _init() -> void:
	Continuum = preload('res://spacetime_bindings/schema/module_continuum_client.gd').new()
	add_child(Continuum)
